title: Configuration
data:
  lead_title: 'Are you lost? Or just breaking the rules?'
  title: '404 Page not found'
  description: 'Our sentinels scanned the area and couldn’t locate the page you’re looking for. It might have been moved, renamed, or decided to go rogue. Don’t worry, though—our system is still solid and we got your back. The button below let’s get you back on track:'
  button_text: 'Back to home'
  button_link: 'entry::home'
  image:
    - 404.png
  copyright_since: 2025
  privacy_statement_type: none
  cookie_notice_type: none
