tabs:
  general:
    display: General
    sections:
      -
        display: '404'
        instructions: 'Configure 404 page content.'
        fields:
          -
            handle: lead_title
            field:
              type: text
              display: 'Lead title'
          -
            handle: title
            field:
              type: text
              display: Title
          -
            handle: description
            field:
              type: textarea
              display: Description
          -
            handle: button_text
            field:
              type: text
              display: 'Button text'
          -
            handle: button_link
            field:
              type: link
              display: 'Button link'
          -
            handle: image
            field:
              container: images
              type: assets
              display: Image
              max_files: 1
      -
        display: Copyright
        instructions: 'Copyright configuration options.'
        fields:
          -
            handle: copyright_name
            field:
              display: 'Copyright name'
              type: text
              instructions: 'Falls back to the application name.'
              width: 50
          -
            handle: copyright_since
            field:
              placeholder: '2020'
              input_type: number
              character_limit: 4
              prepend: ©
              default: '2020'
              display: 'Copyright since'
              instructions: 'The website will add ` - current_year ` if they differ.'
              type: text
              width: 50
              validate:
                - required
      -
        display: 'Privacy statement'
        instructions: 'Configure an optional privacy statement.'
        fields:
          -
            handle: privacy_statement_type
            field:
              options:
                -
                  key: none
                  value: None
                -
                  key: entry
                  value: Entry
                -
                  key: pdf
                  value: PDF
              default: none
              type: button_group
              instructions: 'Form consent fields will link to this Privacy Policy.'
              instructions_position: below
              listable: false
              localizable: true
              display: 'Privacy statement'
              width: 50
          -
            handle: privacy_statement_asset
            field: common.image
            config:
              container: files
              localizable: true
              listable: hidden
              display: 'Privacy statement (PDF)'
              width: 50
              validate:
                - 'required_if:privacy_statement_type,pdf'
              if:
                privacy_statement_type: 'equals pdf'
          -
            handle: privacy_statement_entry
            field: common.entry
            config:
              localizable: true
              listable: hidden
              display: 'Privacy statement (entry)'
              width: 50
              if:
                privacy_statement_type: 'equals entry'
              validate:
                - 'required_if:privacy_statement_type,entry'
      -
        display: 'General Terms'
        fields:
          -
            handle: general_terms_type
            field:
              options:
                -
                  key: none
                  value: None
                -
                  key: entry
                  value: Entry
                -
                  key: pdf
                  value: PDF
              type: button_group
              display: 'General terms'
              width: 50
          -
            handle: general_terms_asset
            field:
              max_files: 1
              container: files
              type: assets
              display: 'General Terms (PDF)'
              width: 50
              if:
                general_terms_type: 'equals pdf'
          -
            handle: general_terms_entry
            field:
              max_items: 1
              type: entries
              display: 'General Terms (entry)'
              if:
                general_terms_type: 'equals entry'
              width: 50
      -
        display: 'Cookie notice'
        instructions: 'Configure an optional cookie notice.'
        fields:
          -
            handle: cookie_notice_type
            field:
              options:
                none: None
                entry: Entry
                pdf: PDF
              default: none
              type: button_group
              instructions: 'The Cookie Banner will link to this Cookie Notice.'
              instructions_position: below
              listable: false
              localizable: true
              display: 'Cookie notice'
              width: 50
          -
            handle: cookie_notice_asset
            field: common.image
            config:
              container: files
              localizable: true
              listable: hidden
              display: 'Cookie notice (PDF)'
              width: 50
              if:
                cookie_notice_type: 'equals pdf'
              validate:
                - 'required_if:cookie_notice_type,pdf'
          -
            handle: cookie_notice_entry
            field: common.entry
            config:
              localizable: true
              listable: hidden
              display: 'Cookie notice (entry)'
              width: 50
              if:
                cookie_notice_type: 'equals entry'
              validate:
                - 'required_if:cookie_notice_type,entry'
