title: Product
fields:
  -
    handle: lead_title
    field:
      type: text
      display: 'Lead title'
  -
    handle: title
    field:
      type: text
      display: Title
  -
    handle: description
    field:
      type: textarea
      display: Description
  -
    handle: image
    field:
      max_files: 1
      container: images
      type: assets
      display: Image
  -
    handle: usps
    field:
      type: replicator
      display: "USP's"
      sets:
        usps:
          display: "USP's"
          sets:
            new_set:
              display: 'New Set'
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Title
                -
                  handle: description
                  field:
                    type: textarea
                    display: Description
  -
    handle: button_text
    field:
      type: text
      display: 'Button text'
      width: 50
  -
    handle: button_link
    field:
      type: link
      display: 'Button link'
      width: 50
